server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/junbi_dev?createDatabaseIfNotExist=true
    username: root
    password: Dev!@#Junbi3306
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8686/realms/demo-realm

keycloak:
  realm: demo-realm
  auth-server-url: http://localhost:8686
  client-id: demo-client
